name: Linting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    name: Lint artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - shell: bash
        run: |
          shellcheck "${GITHUB_WORKSPACE}"/*.sh
