name: Linting

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  linting:
    name: Lint artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - shell: bash
        run: |
          shellcheck "${GITHUB_WORKSPACE}"/*.sh
