name: Requirements tracing

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tracing:
    name: Run OpenFastTrace
    runs-on: ubuntu-latest
    outputs:
      tracing-report-url: ${{ steps.upload-report.outputs.artifact-url }}
    env:
      REPORT_FILENAME: "requirements-tracing-report.html"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run OpenFastTrace
        id: run-oft
        uses: ./
        with:
          report-filename: ${{ env.REPORT_FILENAME }}
          report-format: "html"
          file-patterns: ${{ github.workspace }}

      - name: Upload tracing report
        id: upload-report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tracing-report
          path: ${{ env.REPORT_FILENAME }}

      - name: "Determine exit code"
        run: |
          exit ${{ steps.run-oft.outputs.oft-exit-code }}
